In [3]:
# ví dụ 3.3.2.3: 
import numpy as np 
A= np.arange(10)
A 
a=A[:5] #5 phần tử đầu tiên của mảng
b=A[5:] # các phần tử sau vị trí số 5 
c=A[4:7] # lấy phần tử từ vị trí 5-7 
print(a)
print(b)
print(c)


[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [7]:
#ví dụ 3.3.2.4  Mảng con đa chiều 
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B
a=B[:2,:3] #2 dòng 3 cột 
b=B[:3,::2] 
c=B[::-1,::-1]
print(a)
print(b)
print(c)

[[1 2 3]
 [5 6 7]]
[[1 3]
 [5 7]
 [9 1]]
[[2 1 0 9]
 [8 7 6 5]
 [4 3 2 1]]


In [8]:
# vd 3.3.2.5 
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) 
arr 
print("Cột đầu tiên của mảng arr là: ",arr[:,0]) 
print("Hàng đầu tiên của mảng arr là:",arr[0,:]) 
print("Hàng đầu tiên của mảng arr là:",arr[0]) 

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


In [10]:
import numpy as np 
arr_2d =np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr_view = arr_2d[:2, :2].view() 
arr_view[0, 0] = 100 
print(arr_view)  


print("Mảng gốc sau khi thay đổi giá trị trong view:") 
print(arr_2d) 


[[100   2]
 [  4   5]]
Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [11]:
# vd 3.3.3.2
sub_arr=arr[:2,:2] 
print(sub_arr)
sub_arr[0,0]=10 
print(sub_arr)  
print(arr)

[[1 2]
 [4 5]]
[[10  2]
 [ 4  5]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#vd3.3.3.3
sub_arr_copy=arr[:2,:2].copy() 
print(sub_arr_copy) 
sub_arr_copy[0,0]=10
print(sub_arr_copy) 
print(arr)

[[10  2]
 [ 4  5]]
[[10  2]
 [ 4  5]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#vd 3.3.3.4
arr=np.arange(1,10)
grid=arr.reshape((3,3)) #chuyen arr thanh mang 3x3
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# vd 3.3.3.5 
x=np.array([1,2,3])

print(x.reshape((1,3)) )# tạo ma trận hàng thông qua reshape 

print(x[np.newaxis,:]) # tạo ma trận hàng bằng newaxis 

print(x.reshape((3, 1)) ) # tạo ma trận cột bằng reshape 

print(x[:,np.newaxis] )



[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [ ]:
#vd 3.3.4.1
x=np.array([1,2,3])
y=np.array([4,5,6]) 
xy= np.concatenate([x,y])
print(xy)


a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
c=np.concatenate((a,b))
print(c)



#axis =0 kết hợp theo hàng , axis =1 kết hợp theo cột 
d = np.concatenate([a, b], axis=1) 
print(d)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
