In [3]:
# ví dụ 3.3.2.3: 
import numpy as np 
A= np.arange(10)
A 
a=A[:5] #5 phần tử đầu tiên của mảng
b=A[5:] # các phần tử sau vị trí số 5 
c=A[4:7] # lấy phần tử từ vị trí 5-7 
print(a)
print(b)
print(c)


[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [7]:
#ví dụ 3.3.2.4  Mảng con đa chiều 
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B
a=B[:2,:3] #2 dòng 3 cột 
b=B[:3,::2] 
c=B[::-1,::-1]
print(a)
print(b)
print(c)

[[1 2 3]
 [5 6 7]]
[[1 3]
 [5 7]
 [9 1]]
[[2 1 0 9]
 [8 7 6 5]
 [4 3 2 1]]


In [8]:
# vd 3.3.2.5 
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) 
arr 
print("Cột đầu tiên của mảng arr là: ",arr[:,0]) 
print("Hàng đầu tiên của mảng arr là:",arr[0,:]) 
print("Hàng đầu tiên của mảng arr là:",arr[0]) 

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


In [10]:
import numpy as np 
arr_2d =np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr_view = arr_2d[:2, :2].view() 
arr_view[0, 0] = 100 
print(arr_view)  


print("Mảng gốc sau khi thay đổi giá trị trong view:") 
print(arr_2d) 


[[100   2]
 [  4   5]]
Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [11]:
# vd 3.3.3.2
sub_arr=arr[:2,:2] 
print(sub_arr)
sub_arr[0,0]=10 
print(sub_arr)  
print(arr)

[[1 2]
 [4 5]]
[[10  2]
 [ 4  5]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#vd3.3.3.3
sub_arr_copy=arr[:2,:2].copy() 
print(sub_arr_copy) 
sub_arr_copy[0,0]=10
print(sub_arr_copy) 
print(arr)

[[10  2]
 [ 4  5]]
[[10  2]
 [ 4  5]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#vd 3.3.3.4
arr=np.arange(1,10)
grid=arr.reshape((3,3)) #chuyen arr thanh mang 3x3
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# vd 3.3.3.5 
x=np.array([1,2,3])

print(x.reshape((1,3)) )# tạo ma trận hàng thông qua reshape 

print(x[np.newaxis,:]) # tạo ma trận hàng bằng newaxis 

print(x.reshape((3, 1)) ) # tạo ma trận cột bằng reshape 

print(x[:,np.newaxis] )



[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [23]:
#vd 3.3.4.1
x=np.array([1,2,3])
y=np.array([4,5,6]) 
xy= np.concatenate([x,y])
print(xy)


a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
c=np.concatenate((a,b))
print(c)



#axis =0 kết hợp theo hàng , axis =1 kết hợp theo cột 
d = np.concatenate([a, b], axis=1) 
print(d)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#vd 3.3.4.2
#vstack xếp theo cột (chiều dọc)
#hsatck xếp theo hàng (chiều ngang )
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
c=np.vstack((a,b))
d = np.hstack((a,b)) 
print(c) 
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# vd 3.3.4.3
# split(): tách 
import numpy as np 
arr = np.arange(10)  
sub_arr1=np.split(arr,[3, 6]) 
 
sub_arr2=np.split(arr,2)  
print("Mảng con sub_arr1 là:", sub_arr1, "\n") 
print("Mảng con sub_arr2 là:", sub_arr2) 


Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [26]:
# vd 3.3.4.3 
import numpy as np 
arr = np.arange(16).reshape((4,4)) 
arr 

upper,lower = np.vsplit(arr,2) #Tách theo trục ngang 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(upper,"\n") 
print(lower,"\n") 

left,right=np.hsplit(arr,2)   #Tách theo trục dọc 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(left,"\n") 
print(right,"\n")


Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 

Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



In [27]:
# vd 3.3.5.1

arr = np.array([1, 2, 3, 4, 5]) 
new_element = 10 
index_to_insert = 2 
 
new_arr = np.insert(arr, index_to_insert, new_element) 
 
print(new_arr)   

arr_2d = np.array([[1, 2], [3, 4], [5, 6]]) 
new_element = [7, 8] 
row_to_insert = 1 
 
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0) 
print(new_arr_2d)

[ 1  2 10  3  4  5]
[[1 2]
 [7 8]
 [3 4]
 [5 6]]


In [ ]:
# vd 3.3.6.1
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều: 
 
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.where(arr==3) # chỉ mục của phần tử số 3
indices

In [ ]:
# vd 3.3.6.2
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.argwhere(arr==3)
indices 


array([[2]])

In [ ]:
#vd 3.3.6.3 chỉ mục của phần tử lớn nhất và nhỏ nhất
arr = np.array([1, 5, 2, 3, 4]) 
max_idx = np.argmax(arr) 
min_idx = np.argmin(arr) 
 
print(max_idx) 
print(min_idx) 


1
0


In [34]:
# vd 3.3.5.4 sắp xếp mảng
arr = np.array([1, 2, 3, 4, 5]) 
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [35]:
# theo chiều giảm
arr = np.array([3, 1, 4, 2, 5]) 
sorted_arr_descending= np.sort(arr)[::-1] 
 
sorted_arr_descending


arr = np.array([3, 1, 4, 2, 5]) 
arr.sort()                   
 
arr[::-1] 


array([5, 4, 3, 2, 1])

In [ ]:
# vd 3.3.7.1 
#Xóa một phần tử ở vị trí trong mảng 
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = 2             #Xóa phần tử 4 ở chỉ mục 2. 
new_arr=np.delete(arr,idx_to_delete) 
new_arr



array([3, 4, 5])

In [39]:
#Xóa nhiểu phần tử trong mảng 
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = [1, 3] 
new_arr = np.delete(arr, idx_to_delete) 
 
new_arr

array([3, 4, 5])

In [41]:
#Xóa phần tử trên mảng 2 chiều 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
row_idx_to_delete = 1 
 
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)
new_arr_2d

array([[1, 2, 3],
       [7, 8, 9]])

In [1]:
# vd 3.3.7.2
arr = np.array([1, 2, 3, 4, 5]) 
del arr 
arr  
 


NameError: name 'np' is not defined

In [43]:
#vd 3.3.7.3
arr = np.array([1, 2, 3, 4, 5]) 
arr = None  
print(arr)


None


In [44]:
import numpy as np 
 
# Định nghĩa kiểu dữ liệu cho một Structured Array 
dtype = [('name', 'U20'), ('age', int), ('height', float)] 
 
# Tạo một Structured Array 
data = np.array([('Minh', 22, 181.3), 
                 ('Lan', 40, 160.6), 
                 ('Linh', 31, 163.2), 
                 ('Lương',18,175.5), 
                 ('Thanh',50, 165.0)], dtype=dtype) 
 
print(data) 
 
print(data.dtype)

[('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]
[('name', '<U20'), ('age', '<i8'), ('height', '<f8')]


In [46]:
# vd 3.3.8.2 
import numpy as np 
 
# Định nghĩa kiểu dữ liệu cho một Structured Array 
dtype = [('name', 'U20'), ('age', int), ('height', float)] 
 
# Tạo một Structured Array 
data = np.array([('Minh', 22, 165.5), 
                 ('Lan', 40, 160.0), 
                 ('Linh', 31, 165.0), 
                 ('Lương',18,166.5), 
                 ('Thanh',50, 170.0)], dtype=dtype)
# Truy cập các trường bằng tên 
print(data['name'])    # In ra mảng 'name' 
print(data['age'])     # In ra mảng 'age' 
print(data['height'])  # In ra mảng 'height' 

['Minh' 'Lan' 'Linh' 'Lương' 'Thanh']
[22 40 31 18 50]
[165.5 160.  165.  166.5 170. ]


In [ ]:
# vd 3.4.2 
import numpy as np
import timeit # Import thư viện timeit để đo thời gian thực thi của các đoạn code.

# Tính tổng của mảng sử dụng Numpy
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)"
np_code  = "np_sum = np.sum(np_array)"
np_time  = timeit.timeit(stmt=np_code, setup=np_setup, number=10)

# Tính tổng của danh sách sử dụng List
list_setup = "list_array = list(range(1, 1000001))"
list_code = "list_sum = sum(list_array)"
list_time = timeit.timeit(stmt=list_code, setup=list_setup, number=10)

print("Thời gian tính toán của Numpy:", np_time)
print("Thời gian tính toán của List:", list_time)

print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")


Thời gian tính toán của Numpy: 0.004354499978944659
Thời gian tính toán của List: 0.06969579996075481
Numpy tính nhanh hơn List ở lượt chạy là ~  16 lần!!


In [ ]:
#vd 3.4.3.1
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#Phép Cộng:Sử dụng hàm np.add() hoặc toán tử '+'.
Tong = np.add(arr1,arr2)
#hoặc tong = arr1+arr2

#Phép Trừ: Sử dụng hàm np.subtract() hoặc toán tử '-'.
Hieu = np.subtract(arr1,arr2)
#hoặc Tru = arr1-arr2

#Phép Nhân: Sử dụng hàm np.multiply() hoặc toán tử '*'
Tich = np.multiply(arr1,arr2)
#Hoặc arr1*arr2

#Phép Chia: Sử dụng hàm np.divide() hoặc toán tử '/'
Thuong = np.divide(arr1,arr2)

print("Tổng của arr1 + arr2 là:",Tong)
print("Hiệu của arr1 - arr2 là:",Hieu)
print("Tích của arr1 * arr2 là:",Tich)
print("Thương của arr1/arr2 là:",Thuong)


Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]


In [8]:
#vd 3.4.3.2
import numpy as np 
arr1=np.random.rand(5)
arr1
arr2=np.random.rand(5)
arr2 
arr_maximum=np.maximum(arr1,arr2)
print("Mang ket qua la:",arr_maximum)

Mang ket qua la: [0.94717205 0.82600309 0.79050484 0.89409018 0.76979103]


In [9]:
#vd 3.4.4.1 
import numpy as np
arr1 = np.array([0,1,2])
arr2 = np.array([5,5,5])
arr1 + arr2


array([5, 6, 7])

In [10]:
#vd 3.4.4.2 
import numpy as np
arr1 = np.array([0,1,2])
arr1 + 5


array([5, 6, 7])

In [11]:
#vd 3.4.4.3 
import numpy as np
arr = np.array([0,1,2])
arr
M=np.ones((3,3))
M
arr + M



array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [12]:
#vd 3.4.4.4 
import numpy as np
arr1 = np.arange(3)
arr2=np.arange(3)[:,np.newaxis]

print(arr1)
print(arr2)
arr1 + arr2

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
#vd 3.4.3.3 
import numpy as np

# Tạo mảng dữ liệu với kích thước lớn (1000 phần tử)
data = np.random.randint(100, 200, size=1000)

# Tạo một giá trị trung bình (số thực)
mean_value = np.array([data.mean()])

# Tính tỷ lệ phần trăm tăng trưởng bằng cách áp dụng broadcasting
percentage_growth= (data - mean_value) / mean_value * 100

# In ra 10 phần tử đầu tiên của mảng dữ liệu và tỷ lệ phần trăm tăng trưởng
print("Dữ liệu gốc:", data[:10])
print("Tỷ lệ phần trăm tăng trưởng:", percentage_growth[:10])


Dữ liệu gốc: [108 123 145 168 144 136 166 153 152 149]
Tỷ lệ phần trăm tăng trưởng: [-27.85715717 -17.83731789  -3.14155361  12.22219996  -3.80954289
  -9.15345718  10.88622139   2.20236067   1.53437139  -0.46959647]
